### ISSUE TITLE
Support new `Set(Func<T, T> update)` overload

### ISSUE THREAD

**Issue by linkdotnet** [timonkrebs/MemoizR#34]
There are cases where you are not interested in the absolut value of a signal, but you want to calculate on the current value.

Given a simple `+1` counter or pagination where you are just interested in increasing the value.

## API Proposal
```diff
public sealed class Signal<T> : MemoHandlR<T>
{
+    public async Task Set(Func<T, T> updateFunc);
}
```

Alternatively a new `Update` method could be helpful:
```diff
public sealed class Signal<T> : MemoHandlR<T>
{
+    public async Task Update(Func<T, T> updateFunc);
}
```

**Comment by timonkrebs** [comment]
This already exists: MemoizR/EagerRelativeSignal.cs

**Comment by linkdotnet** [comment]
Fair enough :)
